version: '3'

services:
  database:
    container_name: marketshare_db
    image: mysql:8.0.29
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: marketsharedb